### ISSUE TITLE
Process memory keeps growing, never goes down

### ISSUE THREAD

**Issue by SourceCodeplz** [iamthechad/sslinfo#3]
As soon as I start the Node server it uses 34mb memory, which is fine.
Next step when a query is processed, 59MB and it just stays like that, even though the query is complete.
Then when just using the same query, it goes up to 81MB.
Keeps going like this until it eats all the server memory.

I was looking at a .end method, like the HTTP class but I could not find one for sslinfo.

```
sslinfo.getServerResults({host: ""+id+"", port: 443})
    .done(function (results) {
        response.send(results);
    },
    function (error) {
        console.log("Error", {error: error})
    });
```

Thanks for the help!

**Comment by iamthechad** [comment]
I made changes that helped reduce memory usage in my testing. If this is still an issue, don't hesitate to reopen this. Thanks!

**Comment by SourceCodeplz** [comment]
Memory Leak was not fixed by this update. Problem persists.
Have given the process more than 10 minutes to balance back the memory levels, it didn't.

**Comment by iamthechad** [comment]
Bummer. I'll reopen this and keep looking into it.
